### ISSUE TITLE
UI from omnivore

### ISSUE THREAD

**Issue by Yumega** [JGeek00/my-linkding#20]
The omnivore UI looks better, linkdy can change into similar UI
Thanks 
 
![IMG_8904](https://github.com/JGeek00/linkdy/assets/61570667/b94a803d-1720-4f8f-a72e-6adaf1b2c3dd)

**Comment by JGeek00** [comment]
Linkdy was designed originally with Android in mind, so that's why it uses Material UI. Then, it was also released for iOS because I didn't had to do any extra work. Currently I don't have in mind to redesign the UI.
